import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { sql } from "@/lib/db";
import { recordSystemEvent } from "@/lib/operations";
import { notifyUser } from "@/lib/push-notifications";
import { verifyProviderWebhook } from "@/lib/payment-provider";

type RazorpayEvent={event?:string;payload?:{payment?:{entity?:{id?:string;order_id?:string;method?:string;error_code?:string;error_description?:string}};refund?:{entity?:{id?:string;payment_id?:string;amount?:number;status?:string}}}};

export async function POST(request:Request){const raw=await request.text();if(!verifyProviderWebhook(raw,request.headers.get("x-razorpay-signature")))return NextResponse.json({error:"Invalid webhook signature"},{status:401});let event:RazorpayEvent;try{event=JSON.parse(raw) as RazorpayEvent;}catch{return NextResponse.json({error:"Invalid webhook payload"},{status:400});}const eventId=request.headers.get("x-razorpay-event-id")||createHash("sha256").update(raw).digest("hex");const inserted=await sql(`INSERT INTO pim_v2.payment_webhook_events(provider,event_id,event_type,payload_hash) VALUES('razorpay',$1,$2,$3) ON CONFLICT DO NOTHING RETURNING event_id`,[eventId,event.event||"unknown",createHash("sha256").update(raw).digest("hex")]);if(!inserted.rows[0])return NextResponse.json({received:true,duplicate:true});
 try{const payment=event.payload?.payment?.entity;if(event.event==="payment.captured"&&payment?.order_id&&payment.id){const changed=await sql<{user_id:string;booking_id:string;purpose:string}>(`UPDATE pim_v2.payment_transactions SET provider_payment_id=$2,status='CAPTURED',captured_at=now(),updated_at=now() WHERE provider_order_id=$1 AND status IN ('CREATED','PENDING') RETURNING user_id,booking_id,purpose`,[payment.order_id,payment.id]);const t=changed.rows[0];const method=payment.method?.toLowerCase()==="card"?"CARD":"UPI";if(t?.purpose==="SERVICE_PAYMENT")await sql(`UPDATE pim_v2.bookings SET payment_method=$2,payment_status='CONFIRMED',payment_confirmed_at=now() WHERE id=$1`,[t.booking_id,method]);if(t?.purpose==="CANCELLATION_FEE")await sql(`WITH b AS (UPDATE pim_v2.bookings SET cancellation_fee_status='PAID' WHERE id=$1 RETURNING customer_id),fee AS (UPDATE pim_v2.account_ledger SET status='PAID',settled_at=now() WHERE booking_id=$1 AND entry_type='CANCELLATION_FEE'),comp AS (UPDATE pim_v2.account_ledger SET status='PENDING' WHERE booking_id=$1 AND entry_type='PANDIT_COMPENSATION') SELECT 1`,[t.booking_id]);if(t)await notifyUser(t.user_id,{title:"Payment confirmed",body:"Your payment was securely confirmed.",url:"/customer#live-requests",eventType:"PAYMENT_CAPTURED"});}
  if(event.event==="payment.failed"&&payment?.order_id)await sql(`UPDATE pim_v2.payment_transactions SET status='FAILED',failure_code=$2,failure_description=$3,updated_at=now() WHERE provider_order_id=$1 AND status<>'CAPTURED'`,[payment.order_id,payment.error_code||null,payment.error_description||null]);
  const refund=event.payload?.refund?.entity;if(event.event==="refund.processed"&&refund?.id)await sql(`WITH r AS (UPDATE pim_v2.refunds SET status='COMPLETED',completed_at=now(),updated_at=now() WHERE provider_refund_id=$1 RETURNING payment_transaction_id) UPDATE pim_v2.payment_transactions SET status='REFUNDED',updated_at=now() WHERE id IN (SELECT payment_transaction_id FROM r)`,[refund.id]);
  await sql(`UPDATE pim_v2.payment_webhook_events SET processed_at=now() WHERE provider='razorpay' AND event_id=$1`,[eventId]);return NextResponse.json({received:true});
 }catch(error){await sql(`UPDATE pim_v2.payment_webhook_events SET processing_error=$2 WHERE provider='razorpay' AND event_id=$1`,[eventId,error instanceof Error?error.message:"unknown"]);await recordSystemEvent({severity:"ERROR",source:"payments",eventType:"PAYMENT_WEBHOOK_FAILED",message:"A verified payment webhook could not be processed",metadata:{eventId,eventType:event.event}});return NextResponse.json({error:"Webhook processing failed"},{status:500});}}
