"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ShieldCheck, Trash2, XCircle } from "lucide-react";
import { readJson } from "@/lib/http";

type PrivacyRequest={id:string;request_type:string;status:string;details:string|null;resolution:string|null;requested_at:string;role:string;name:string|null;phone:string|null;email:string|null;account_status:string;active_services:number;outstanding_balance:number};

export function AdminPrivacyRequests({focusRequestId,onChanged}:{focusRequestId?:string|null;onChanged?:()=>void}={}){
  const [items,setItems]=useState<PrivacyRequest[]>([]);const [busy,setBusy]=useState("");const [notice,setNotice]=useState("");
  async function load(){const response=await fetch(`/api/admin/privacy-requests?fresh=${Date.now()}`,{cache:"no-store"});const data=await readJson<{requests?:PrivacyRequest[];error?:string}>(response);if(response.ok)setItems(data.requests??[]);else setNotice(data.error??"Unable to load privacy requests");}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
  useEffect(()=>{if(!focusRequestId)return;const timer=window.setTimeout(()=>document.getElementById(`privacy-request-${focusRequestId}`)?.scrollIntoView({behavior:"smooth",block:"center"}),100);return()=>window.clearTimeout(timer);},[focusRequestId,items]);
  async function act(item:PrivacyRequest,action:"START_REVIEW"|"COMPLETE"|"REJECT"){
    const isAccountDeletion=item.request_type==="ACCOUNT_DELETION";
    const resolution=action==="START_REVIEW"?"":window.prompt(action==="COMPLETE"&&isAccountDeletion?"Record why deletion is approved:":action==="COMPLETE"?"Describe what was deleted or completed:":isAccountDeletion?"Explain why the account will be kept:":"Explain why this request cannot be completed:",action==="COMPLETE"&&isAccountDeletion?"Admin approved account deletion after checking active services and outstanding balances.":"")?.trim();if(action!=="START_REVIEW"&&!resolution)return;
    if(action==="COMPLETE"&&isAccountDeletion&&!window.confirm(`Permanently delete ${item.name??"this user's"} private profile and anonymise the account? Booking, payment and safety records required for audit may remain anonymised. This cannot be undone.`))return;
    setBusy(item.id);const response=await fetch("/api/admin/privacy-requests",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({requestId:item.id,action,resolution})});const data=await readJson<{error?:string}>(response);setNotice(response.ok?isAccountDeletion&&action==="COMPLETE"?"Account deletion approved. The private profile was removed and the account was anonymised.":isAccountDeletion&&action==="REJECT"?"Deletion rejected. The account has been restored.":"Privacy request updated.":data.error??"Unable to update privacy request");setBusy("");await load();if(response.ok)onChanged?.();
  }
  return <section className="history admin-privacy" id="admin-privacy"><div className="section-title"><div><h2>Account and privacy requests</h2><p>Only an authorised Admin can approve account deletion. Every decision is checked and audited.</p></div><ShieldCheck size={22}/></div>{notice&&<div className="alert success">{notice}</div>}{items.length?<div className="admin-privacy-list">{items.map(item=>{const deletion=item.request_type==="ACCOUNT_DELETION";const blocked=Number(item.active_services)>0||Number(item.outstanding_balance)>0;return <article id={`privacy-request-${item.id}`} className={`${deletion?"account-deletion-request":""} ${focusRequestId===item.id?"focused":""}`} key={item.id}><div><strong>{deletion?`${item.role === "PANDIT" ? "Pandit" : "Customer"} account deletion`:item.request_type.replaceAll("_"," ")}</strong><span>{item.role} · {item.name??"Unnamed"} · {item.phone ? `••••${item.phone.slice(-4)}` : item.email ?? "Google account"}</span><small>Requested {new Date(item.requested_at).toLocaleString("en-IN")}</small>{deletion&&<div className={`deletion-safety ${blocked?"blocked":"ready"}`}><b>{blocked?"Approval is currently blocked":"Ready for Admin decision"}</b><span>{Number(item.active_services)} active services · ₹{Number(item.outstanding_balance).toLocaleString("en-IN")} outstanding</span></div>}{item.details&&<p>{item.details}</p>}{item.resolution&&<em>{item.resolution}</em>}</div><span className="status">{item.status.replaceAll("_"," ")}</span><div className="button-row">{item.status==="OPEN"&&<button className="btn btn-ghost" disabled={busy===item.id} onClick={()=>void act(item,"START_REVIEW")}>Start review</button>}{["OPEN","IN_REVIEW"].includes(item.status)&&<><button className="btn btn-ghost danger" disabled={busy===item.id} onClick={()=>void act(item,"REJECT")}>{deletion?<><XCircle size={15}/> Keep account</>:"Reject"}</button><button className="btn btn-primary" disabled={busy===item.id||Boolean(deletion&&blocked)} onClick={()=>void act(item,"COMPLETE")}>{deletion?<><Trash2 size={15}/> Approve deletion</>:<><CheckCircle2 size={15}/> Complete</>}</button></>}</div></article>})}</div>:<div className="empty">No account or privacy requests yet.</div>}</section>;
}
