"use client";
import { useEffect, useRef, useState } from "react";
import { Bell, BellRing, Check, X } from "lucide-react";
import { readJson } from "@/lib/http";

type Item = { id: string; title: string; body: string; url: string; read_at: string | null; created_at: string };
function decodeKey(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); return Uint8Array.from(atob((value + padding).replace(/-/g, "+").replace(/_/g, "/")), (char) => char.charCodeAt(0)); }

let alertAudioContext: AudioContext | null = null;
async function playAlertSound() {
  const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!AudioContextClass) return;
  alertAudioContext ??= new AudioContextClass();
  if (alertAudioContext.state === "suspended") await alertAudioContext.resume();
  const startedAt = alertAudioContext.currentTime;
  [[0, 740], [0.16, 940], [0.34, 1120]].forEach(([delay, frequency]) => {
    const oscillator = alertAudioContext!.createOscillator(); const gain = alertAudioContext!.createGain();
    oscillator.type = "sine"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0.0001, startedAt + delay); gain.gain.exponentialRampToValueAtTime(0.18, startedAt + delay + 0.02); gain.gain.exponentialRampToValueAtTime(0.0001, startedAt + delay + 0.13); oscillator.connect(gain).connect(alertAudioContext!.destination); oscillator.start(startedAt + delay); oscillator.stop(startedAt + delay + 0.14);
  });
}

export function NotificationCenter() {
  const [items, setItems] = useState<Item[]>([]); const [unread, setUnread] = useState(0); const [open, setOpen] = useState(false); const [enabled, setEnabled] = useState(false); const [key, setKey] = useState(""); const [message, setMessage] = useState("");
  const latestId = useRef<string | null>(null);
  async function load() { const [response, keyResponse] = await Promise.all([fetch("/api/notifications", { cache: "no-store" }), fetch("/api/notifications/public-key")]); if (keyResponse.ok) { const config = await readJson<{ vapidPublicKey?: string }>(keyResponse); setKey(config.vapidPublicKey ?? ""); } if (!response.ok) return; const data = await readJson<{ notifications?: Item[]; unread?: number; vapidPublicKey?: string }>(response); const nextItems = data.notifications ?? []; if (latestId.current && nextItems[0]?.id && latestId.current !== nextItems[0].id && localStorage.getItem("panditconnect-notification-sound") === "on") void playAlertSound(); latestId.current = nextItems[0]?.id ?? latestId.current; setItems(nextItems); setUnread(data.unread ?? 0); setKey((current) => data.vapidPublicKey || current); }
  useEffect(() => { const onPush = () => { if (localStorage.getItem("panditconnect-notification-sound") === "on") void playAlertSound(); void load(); }; const initial = window.setTimeout(() => void load(), 0); if ("serviceWorker" in navigator) void navigator.serviceWorker.register("/sw.js").then(async (registration) => setEnabled(Boolean(await registration.pushManager.getSubscription()))); navigator.serviceWorker?.addEventListener("message", onPush); const timer = window.setInterval(() => void load(), 15000); return () => { window.clearTimeout(initial); window.clearInterval(timer); navigator.serviceWorker?.removeEventListener("message", onPush); }; }, []);
  async function enable() { setMessage(""); await playAlertSound(); if (!("serviceWorker" in navigator) || !("PushManager" in window)) { setMessage("Push notifications are not supported in this browser."); return; } if (!key) { setMessage("Device notifications are being configured. Please try again shortly."); return; } const permission = await Notification.requestPermission(); if (permission !== "granted") { setMessage("Allow notifications in your browser settings to receive updates."); return; } const registration = await navigator.serviceWorker.ready; const existing = await registration.pushManager.getSubscription(); const subscription = existing ?? await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: decodeKey(key) }); const response = await fetch("/api/notifications/subscription", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(subscription.toJSON()) }); if (!response.ok) { setMessage("Could not connect this device. Please try again."); return; } localStorage.setItem("panditconnect-notification-sound", "on"); setEnabled(true); setMessage("Notifications and alert sound enabled on this device."); }
  async function show() { setOpen(true); if (enabled) { localStorage.setItem("panditconnect-notification-sound", "on"); await playAlertSound(); } if (unread) { await fetch("/api/notifications", { method: "PATCH" }); setUnread(0); setItems((old) => old.map((item) => ({ ...item, read_at: item.read_at || new Date().toISOString() }))); } }
  return <div className="notification-center"><button className="icon-button notification-button" onClick={() => open ? setOpen(false) : void show()} aria-label="Notifications">{unread ? <BellRing size={18} /> : <Bell size={18} />}{unread > 0 && <b>{Math.min(unread, 9)}{unread > 9 ? "+" : ""}</b>}</button>{open && <section className="notification-panel"><header><div><strong>Notifications</strong><small>Updates for this account</small></div><button className="icon-button" onClick={() => setOpen(false)} aria-label="Close notifications"><X size={16} /></button></header>{!enabled ? <div className="notification-permission"><BellRing size={19} /><div><strong>Never miss an urgent update</strong><small>Receive booking, chat and review alerts with sound on this device.</small></div><button onClick={() => void enable()}>Enable</button></div> : <p className="notification-message"><Check size={14} />Device alerts and in-app sound are on.</p>}{message && <p className="notification-message"><Check size={14} />{message}</p>}<div className="notification-list">{items.length ? items.map((item) => <a href={item.url} key={item.id} className={!item.read_at ? "unread" : ""}><strong>{item.title}</strong><span>{item.body}</span><small>{new Date(item.created_at).toLocaleString("en-IN")}</small></a>) : <p className="notification-empty">No notifications yet.</p>}</div></section>}</div>;
}
