"use client";
import { useEffect, useState } from "react";
import { Headphones, ShieldAlert } from "lucide-react";
import { readJson } from "@/lib/http";

type SupportCase = { id:string; category:string; subject:string; priority:string; status:string; resolution:string|null; created_at:string };
type BookingOption = { id:string; service_name:string; status:string };
export function SupportCenter({ bookings=[] }: { bookings?:BookingOption[] }) {
  const [cases,setCases]=useState<SupportCase[]>([]); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const [category,setCategory]=useState("BOOKING"); const [bookingId,setBookingId]=useState(""); const [subject,setSubject]=useState(""); const [description,setDescription]=useState("");
  async function load(){const response=await fetch("/api/support-cases",{cache:"no-store"});const data=await readJson<{cases?:SupportCase[]}>(response);if(response.ok)setCases(data.cases??[]);}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
  async function submit(){setBusy(true);setMessage("");const response=await fetch("/api/support-cases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({category,bookingId:bookingId||undefined,subject,description})});const data=await readJson<{error?:string}>(response);if(!response.ok)setMessage(data.error??"Unable to create support case");else{setMessage("Support case created. Our operations team can now track it.");setSubject("");setDescription("");setBookingId("");await load();}setBusy(false);}
  return <section className="history support-center" id="support"><div className="section-title"><div><h2>Help and safety</h2><p>Report a no-show, service issue, account problem or safety concern.</p></div><button className="btn btn-ghost" onClick={()=>setOpen(!open)}><Headphones size={16}/>{open?"Close form":"Contact support"}</button></div>
    {open&&<div className="support-form"><label>Issue type<select value={category} onChange={e=>setCategory(e.target.value)}><option value="BOOKING">Booking problem</option><option value="NO_SHOW">Pandit/customer did not arrive</option><option value="SERVICE_QUALITY">Service quality</option><option value="CHAT">Online chat</option><option value="ACCOUNT">Account access</option><option value="SAFETY">Urgent safety concern</option><option value="OTHER">Other</option></select></label>{bookings.length>0&&<label>Related booking<select value={bookingId} onChange={e=>setBookingId(e.target.value)}><option value="">No booking selected</option>{bookings.slice(0,20).map(b=><option key={b.id} value={b.id}>{b.service_name} · {b.status}</option>)}</select></label>}<label>Subject<input maxLength={120} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Short summary"/></label><label className="wide">What happened?<textarea rows={4} maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Share the facts and what help you need."/></label>{category==="SAFETY"&&<div className="alert error wide"><ShieldAlert size={17}/>If anyone is in immediate danger, contact local emergency services first.</div>}<button className="btn btn-primary" disabled={busy||subject.trim().length<5||description.trim().length<10} onClick={submit}>{busy?"Submitting…":"Create support case"}</button>{message&&<p className="support-message">{message}</p>}</div>}
    <div className="support-case-list">{cases.slice(0,5).map(item=><article key={item.id}><div><strong>{item.subject}</strong><span>{item.category.replaceAll("_"," ")} · {new Date(item.created_at).toLocaleDateString("en-IN")}</span>{item.resolution&&<small>{item.resolution}</small>}</div><span className={`status ${item.priority==="URGENT"?"urgent":""}`}>{item.status.replaceAll("_"," ")}</span></article>)}</div>
  </section>;
}
