export type PortalCopy = {
  home: string; bookPandit: string; askOnline: string; myBookings: string;
  today: string; requests: string; chat: string; namaste: string; signedInAs: string;
  language: string;
};

const english: PortalCopy = { home:"Home",bookPandit:"Book Pandit",askOnline:"Ask online",myBookings:"My bookings",today:"Today",requests:"Requests",chat:"Chat",namaste:"Namaste",signedInAs:"Signed in as",language:"Language" };

export const PORTAL_TRANSLATIONS: Record<string, PortalCopy> = {
  English: english,
  Hindi: { home:"मुखपृष्ठ",bookPandit:"पंडित बुक करें",askOnline:"ऑनलाइन पूछें",myBookings:"मेरी बुकिंग",today:"आज",requests:"अनुरोध",chat:"चैट",namaste:"नमस्ते",signedInAs:"साइन इन",language:"भाषा" },
  Marathi: { home:"मुख्यपृष्ठ",bookPandit:"पंडित बुक करा",askOnline:"ऑनलाइन विचारा",myBookings:"माझ्या बुकिंग",today:"आज",requests:"विनंत्या",chat:"चॅट",namaste:"नमस्कार",signedInAs:"साइन इन",language:"भाषा" },
  Gujarati: { home:"મુખ્ય પૃષ્ઠ",bookPandit:"પંડિત બુક કરો",askOnline:"ઑનલાઇન પૂછો",myBookings:"મારી બુકિંગ",today:"આજે",requests:"વિનંતીઓ",chat:"ચેટ",namaste:"નમસ્તે",signedInAs:"સાઇન ઇન",language:"ભાષા" },
  Bengali: { home:"হোম",bookPandit:"পণ্ডিত বুক করুন",askOnline:"অনলাইনে জিজ্ঞাসা",myBookings:"আমার বুকিং",today:"আজ",requests:"অনুরোধ",chat:"চ্যাট",namaste:"নমস্কার",signedInAs:"সাইন ইন",language:"ভাষা" },
  Tamil: { home:"முகப்பு",bookPandit:"பண்டிதரை முன்பதிவு செய்க",askOnline:"ஆன்லைனில் கேளுங்கள்",myBookings:"எனது முன்பதிவுகள்",today:"இன்று",requests:"கோரிக்கைகள்",chat:"அரட்டை",namaste:"வணக்கம்",signedInAs:"உள்நுழைந்தவர்",language:"மொழி" },
  Telugu: { home:"హోమ్",bookPandit:"పండిత్‌ను బుక్ చేయండి",askOnline:"ఆన్‌లైన్‌లో అడగండి",myBookings:"నా బుకింగ్‌లు",today:"ఈ రోజు",requests:"అభ్యర్థనలు",chat:"చాట్",namaste:"నమస్కారం",signedInAs:"సైన్ ఇన్",language:"భాష" },
  Malayalam: { home:"ഹോം",bookPandit:"പണ്ഡിറ്റിനെ ബുക്ക് ചെയ്യുക",askOnline:"ഓൺലൈനിൽ ചോദിക്കുക",myBookings:"എന്റെ ബുക്കിംഗുകൾ",today:"ഇന്ന്",requests:"അഭ്യർത്ഥനകൾ",chat:"ചാറ്റ്",namaste:"നമസ്കാരം",signedInAs:"സൈൻ ഇൻ",language:"ഭാഷ" },
  Kannada: { home:"ಮುಖಪುಟ",bookPandit:"ಪಂಡಿತರನ್ನು ಬುಕ್ ಮಾಡಿ",askOnline:"ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಕೇಳಿ",myBookings:"ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು",today:"ಇಂದು",requests:"ವಿನಂತಿಗಳು",chat:"ಚಾಟ್",namaste:"ನಮಸ್ಕಾರ",signedInAs:"ಸೈನ್ ಇನ್",language:"ಭಾಷೆ" },
  Punjabi: { home:"ਮੁੱਖ ਪੰਨਾ",bookPandit:"ਪੰਡਿਤ ਬੁੱਕ ਕਰੋ",askOnline:"ਆਨਲਾਈਨ ਪੁੱਛੋ",myBookings:"ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ",today:"ਅੱਜ",requests:"ਬੇਨਤੀਆਂ",chat:"ਚੈਟ",namaste:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ",signedInAs:"ਸਾਈਨ ਇਨ",language:"ਭਾਸ਼ਾ" },
  Odia: { home:"ମୁଖ୍ୟ ପୃଷ୍ଠା",bookPandit:"ପଣ୍ଡିତ ବୁକ୍ କରନ୍ତୁ",askOnline:"ଅନଲାଇନରେ ପଚାରନ୍ତୁ",myBookings:"ମୋ ବୁକିଂ",today:"ଆଜି",requests:"ଅନୁରୋଧ",chat:"ଚାଟ୍",namaste:"ନମସ୍କାର",signedInAs:"ସାଇନ୍ ଇନ୍",language:"ଭାଷା" },
  Urdu: { home:"ہوم",bookPandit:"پنڈت بک کریں",askOnline:"آن لائن پوچھیں",myBookings:"میری بکنگ",today:"آج",requests:"درخواستیں",chat:"چیٹ",namaste:"نمستے",signedInAs:"سائن ان",language:"زبان" },
};

export const portalCopy = (language: string) => PORTAL_TRANSLATIONS[language] ?? english;

const CUSTOMER_HOME_TRANSLATIONS: Record<string, Record<string, string>> = {
  Hindi: {
    "Puja help for your family":"आपके परिवार के लिए पूजा सहायता","Book a verified nearby Pandit in a few simple steps.":"कुछ आसान चरणों में नज़दीकी सत्यापित पंडित बुक करें।","Puja help":"पूजा सहायता","What do you need help with today?":"आज आपको किस सहायता की आवश्यकता है?","Choose one option below. You do not need to know the Puja name—we will guide the rest.":"नीचे एक विकल्प चुनें। पूजा का नाम जानना आवश्यक नहीं है—हम आगे आपका मार्गदर्शन करेंगे।","Best place to start":"शुरू करने का सबसे आसान तरीका","Help me choose and book":"चुनने और बुक करने में मेरी मदद करें","Describe the occasion in simple words":"अवसर को सरल शब्दों में बताएं","Describe":"बताएं","Choose":"चुनें","Confirm":"पुष्टि करें","Nearby verified Pandits":"नज़दीकी सत्यापित पंडित","Choose someone your family can trust":"ऐसे पंडित को चुनें जिन पर आपका परिवार भरोसा कर सके","Only approved, online Pandits inside their service area are shown.":"केवल स्वीकृत और ऑनलाइन पंडित दिखाए जाते हैं जो आपके क्षेत्र में सेवा देते हैं।","Quick help":"त्वरित सहायता","Choose what you need now":"अभी अपनी आवश्यकता चुनें","Nothing is submitted until you confirm.":"आपकी पुष्टि से पहले कुछ भी भेजा नहीं जाएगा।","Plan ahead":"पहले से योजना बनाएं","Schedule a Puja":"पूजा का समय तय करें","Urgent help":"तत्काल सहायता","My Pandit cancelled":"मेरे पंडित ने रद्द कर दिया","Quickly find another approved Pandit nearby.":"नज़दीक दूसरा स्वीकृत पंडित जल्दी खोजें।","Online guidance":"ऑनलाइन मार्गदर्शन","Chat with a Pandit":"पंडित से चैट करें","Ask a religious question privately online.":"धार्मिक प्रश्न निजी रूप से ऑनलाइन पूछें।"
  },
  Marathi: {
    "Puja help for your family":"तुमच्या कुटुंबासाठी पूजा सहाय्य","Book a verified nearby Pandit in a few simple steps.":"काही सोप्या टप्प्यांत जवळचे सत्यापित पंडित बुक करा.","Puja help":"पूजा सहाय्य","What do you need help with today?":"आज तुम्हाला कशासाठी मदत हवी आहे?","Choose one option below. You do not need to know the Puja name—we will guide the rest.":"खाली एक पर्याय निवडा. पूजेचे नाव माहित असणे आवश्यक नाही—पुढे आम्ही मार्गदर्शन करू.","Best place to start":"सुरुवात करण्याचा सोपा मार्ग","Help me choose and book":"निवड आणि बुकिंगसाठी मदत करा","Describe the occasion in simple words":"प्रसंग सोप्या शब्दांत सांगा","Describe":"सांगा","Choose":"निवडा","Confirm":"पुष्टी करा","Nearby verified Pandits":"जवळचे सत्यापित पंडित","Choose someone your family can trust":"तुमच्या कुटुंबाला विश्वास वाटेल असे पंडित निवडा","Only approved, online Pandits inside their service area are shown.":"फक्त मंजूर, ऑनलाइन आणि तुमच्या भागात सेवा देणारे पंडित दाखवले जातात.","Quick help":"त्वरित मदत","Choose what you need now":"आता तुम्हाला काय हवे ते निवडा","Nothing is submitted until you confirm.":"तुम्ही पुष्टी करेपर्यंत काहीही पाठवले जाणार नाही.","Plan ahead":"आधीच नियोजन करा","Schedule a Puja":"पूजेची वेळ ठरवा","Urgent help":"तातडीची मदत","My Pandit cancelled":"माझ्या पंडितांनी रद्द केले","Quickly find another approved Pandit nearby.":"जवळचे दुसरे मंजूर पंडित पटकन शोधा.","Online guidance":"ऑनलाइन मार्गदर्शन","Chat with a Pandit":"पंडितांशी चॅट करा","Ask a religious question privately online.":"धार्मिक प्रश्न ऑनलाइन खासगीपणे विचारा."
  },
  Gujarati: {
    "Puja help for your family":"તમારા પરિવાર માટે પૂજા સહાય","Book a verified nearby Pandit in a few simple steps.":"થોડાં સરળ પગલાંમાં નજીકના ચકાસાયેલ પંડિતને બુક કરો.","Puja help":"પૂજા સહાય","What do you need help with today?":"આજે તમને કઈ મદદ જોઈએ છે?","Choose one option below. You do not need to know the Puja name—we will guide the rest.":"નીચે એક વિકલ્પ પસંદ કરો. પૂજાનું નામ જાણવું જરૂરી નથી—અમે આગળ માર્ગદર્શન આપીશું.","Best place to start":"શરૂ કરવા માટે શ્રેષ્ઠ","Help me choose and book":"પસંદ કરવામાં અને બુક કરવામાં મદદ કરો","Describe the occasion in simple words":"પ્રસંગને સરળ શબ્દોમાં જણાવો","Describe":"વર્ણન કરો","Choose":"પસંદ કરો","Confirm":"ખાતરી કરો","Nearby verified Pandits":"નજીકના ચકાસાયેલ પંડિતો","Choose someone your family can trust":"તમારો પરિવાર વિશ્વાસ કરી શકે તેવા પંડિત પસંદ કરો","Only approved, online Pandits inside their service area are shown.":"ફક્ત મંજૂર, ઑનલાઇન અને તમારા વિસ્તારમાં સેવા આપતા પંડિતો બતાવવામાં આવે છે.","Quick help":"ઝડપી મદદ","Choose what you need now":"હમણાં તમને શું જોઈએ છે તે પસંદ કરો","Nothing is submitted until you confirm.":"તમે ખાતરી ન કરો ત્યાં સુધી કંઈ મોકલવામાં આવતું નથી.","Plan ahead":"આગોતરું આયોજન","Schedule a Puja":"પૂજાનો સમય નક્કી કરો","Urgent help":"તાત્કાલિક મદદ","My Pandit cancelled":"મારા પંડિતે રદ કર્યું","Quickly find another approved Pandit nearby.":"નજીકના બીજા મંજૂર પંડિતને ઝડપથી શોધો.","Online guidance":"ઑનલાઇન માર્ગદર્શન","Chat with a Pandit":"પંડિત સાથે ચેટ કરો","Ask a religious question privately online.":"ધાર્મિક પ્રશ્ન ખાનગી રીતે ઑનલાઇન પૂછો."
  },
  Bengali: {
    "Puja help for your family":"আপনার পরিবারের জন্য পূজা সহায়তা","Book a verified nearby Pandit in a few simple steps.":"কয়েকটি সহজ ধাপে কাছের যাচাইকৃত পণ্ডিত বুক করুন।","Puja help":"পূজা সহায়তা","What do you need help with today?":"আজ আপনার কী সাহায্য দরকার?","Choose one option below. You do not need to know the Puja name—we will guide the rest.":"নিচে একটি বিকল্প বেছে নিন। পূজার নাম জানা জরুরি নয়—আমরা পরবর্তী ধাপ দেখাব।","Best place to start":"শুরু করার সহজ উপায়","Help me choose and book":"বেছে নিতে ও বুক করতে সাহায্য করুন","Describe the occasion in simple words":"অনুষ্ঠানটি সহজ ভাষায় বলুন","Describe":"বলুন","Choose":"বেছে নিন","Confirm":"নিশ্চিত করুন","Nearby verified Pandits":"কাছের যাচাইকৃত পণ্ডিত","Choose someone your family can trust":"আপনার পরিবার বিশ্বাস করতে পারে এমন পণ্ডিত বেছে নিন","Only approved, online Pandits inside their service area are shown.":"শুধু অনুমোদিত, অনলাইন এবং আপনার এলাকায় সেবা দেওয়া পণ্ডিত দেখানো হয়।","Quick help":"দ্রুত সাহায্য","Choose what you need now":"এখন আপনার প্রয়োজন বেছে নিন","Nothing is submitted until you confirm.":"আপনি নিশ্চিত না করা পর্যন্ত কিছু পাঠানো হবে না।","Plan ahead":"আগে থেকে পরিকল্পনা","Schedule a Puja":"পূজার সময় নির্ধারণ করুন","Urgent help":"জরুরি সাহায্য","My Pandit cancelled":"আমার পণ্ডিত বাতিল করেছেন","Quickly find another approved Pandit nearby.":"কাছের অন্য অনুমোদিত পণ্ডিত দ্রুত খুঁজুন।","Online guidance":"অনলাইন নির্দেশনা","Chat with a Pandit":"পণ্ডিতের সঙ্গে চ্যাট করুন","Ask a religious question privately online.":"ধর্মীয় প্রশ্ন ব্যক্তিগতভাবে অনলাইনে জিজ্ঞাসা করুন।"
  },
  Tamil: {
    "Puja help for your family":"உங்கள் குடும்பத்திற்கான பூஜை உதவி","Book a verified nearby Pandit in a few simple steps.":"சில எளிய படிகளில் அருகிலுள்ள சரிபார்க்கப்பட்ட பண்டிதரை முன்பதிவு செய்யுங்கள்.","Puja help":"பூஜை உதவி","What do you need help with today?":"இன்று உங்களுக்கு என்ன உதவி தேவை?","Choose one option below. You do not need to know the Puja name—we will guide the rest.":"கீழே ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும். பூஜையின் பெயர் தெரிய வேண்டியதில்லை—அடுத்த படிகளை நாங்கள் வழிகாட்டுவோம்.","Best place to start":"தொடங்க எளிய வழி","Help me choose and book":"தேர்வு செய்து முன்பதிவு செய்ய உதவுங்கள்","Describe the occasion in simple words":"நிகழ்வை எளிய வார்த்தைகளில் சொல்லுங்கள்","Describe":"விவரிக்கவும்","Choose":"தேர்வு","Confirm":"உறுதி","Nearby verified Pandits":"அருகிலுள்ள சரிபார்க்கப்பட்ட பண்டிதர்கள்","Choose someone your family can trust":"உங்கள் குடும்பம் நம்பக்கூடிய பண்டிதரைத் தேர்ந்தெடுக்கவும்","Only approved, online Pandits inside their service area are shown.":"அங்கீகரிக்கப்பட்டு ஆன்லைனில் உள்ள, உங்கள் பகுதியில் சேவை செய்யும் பண்டிதர்கள் மட்டும் காட்டப்படுவர்.","Quick help":"விரைவு உதவி","Choose what you need now":"இப்போது தேவையானதைத் தேர்ந்தெடுக்கவும்","Nothing is submitted until you confirm.":"நீங்கள் உறுதி செய்யும் வரை எதுவும் அனுப்பப்படாது.","Plan ahead":"முன்கூட்டியே திட்டமிடுங்கள்","Schedule a Puja":"பூஜை நேரத்தைத் திட்டமிடுங்கள்","Urgent help":"அவசர உதவி","My Pandit cancelled":"என் பண்டிதர் ரத்து செய்தார்","Quickly find another approved Pandit nearby.":"அருகிலுள்ள மற்றொரு அங்கீகரிக்கப்பட்ட பண்டிதரை விரைவாகக் கண்டறியுங்கள்.","Online guidance":"ஆன்லைன் வழிகாட்டுதல்","Chat with a Pandit":"பண்டிதருடன் உரையாடுங்கள்","Ask a religious question privately online.":"மதக் கேள்வியை தனிப்பட்ட முறையில் ஆன்லைனில் கேளுங்கள்."
  },
  Telugu: {
    "Puja help for your family":"మీ కుటుంబానికి పూజ సహాయం","Book a verified nearby Pandit in a few simple steps.":"కొన్ని సులభమైన దశల్లో సమీపంలోని ధృవీకరించిన పండితుడిని బుక్ చేయండి.","Puja help":"పూజ సహాయం","What do you need help with today?":"ఈ రోజు మీకు ఏ సహాయం కావాలి?","Choose one option below. You do not need to know the Puja name—we will guide the rest.":"కింద ఒక ఎంపికను ఎంచుకోండి. పూజ పేరు తెలియాల్సిన అవసరం లేదు—తర్వాతి దశలను మేము చూపిస్తాము.","Best place to start":"ప్రారంభించడానికి సులభమైన మార్గం","Help me choose and book":"ఎంచుకుని బుక్ చేయడంలో సహాయం చేయండి","Describe the occasion in simple words":"సందర్భాన్ని సులభమైన మాటల్లో చెప్పండి","Describe":"వివరించండి","Choose":"ఎంచుకోండి","Confirm":"నిర్ధారించండి","Nearby verified Pandits":"సమీపంలోని ధృవీకరించిన పండితులు","Choose someone your family can trust":"మీ కుటుంబం నమ్మగల పండితుడిని ఎంచుకోండి","Only approved, online Pandits inside their service area are shown.":"ఆమోదించబడిన, ఆన్‌లైన్‌లో ఉన్న మరియు మీ ప్రాంతంలో సేవలందించే పండితులు మాత్రమే చూపబడతారు.","Quick help":"త్వరిత సహాయం","Choose what you need now":"ఇప్పుడు మీకు కావలసింది ఎంచుకోండి","Nothing is submitted until you confirm.":"మీరు నిర్ధారించే వరకు ఏదీ పంపబడదు.","Plan ahead":"ముందుగానే ప్లాన్ చేయండి","Schedule a Puja":"పూజ సమయాన్ని నిర్ణయించండి","Urgent help":"అత్యవసర సహాయం","My Pandit cancelled":"నా పండితుడు రద్దు చేశారు","Quickly find another approved Pandit nearby.":"సమీపంలో మరో ఆమోదిత పండితుడిని త్వరగా కనుగొనండి.","Online guidance":"ఆన్‌లైన్ మార్గదర్శనం","Chat with a Pandit":"పండితుడితో చాట్ చేయండి","Ask a religious question privately online.":"మతపరమైన ప్రశ్నను వ్యక్తిగతంగా ఆన్‌లైన్‌లో అడగండి."
  },
  Malayalam: {
    "Puja help for your family":"നിങ്ങളുടെ കുടുംബത്തിനുള്ള പൂജ സഹായം","Book a verified nearby Pandit in a few simple steps.":"കുറച്ച് ലളിതമായ ഘട്ടങ്ങളിൽ അടുത്തുള്ള പരിശോധിച്ച പണ്ഡിറ്റിനെ ബുക്ക് ചെയ്യൂ.","Puja help":"പൂജ സഹായം","What do you need help with today?":"ഇന്ന് നിങ്ങൾക്ക് എന്ത് സഹായമാണ് വേണ്ടത്?","Choose one option below. You do not need to know the Puja name—we will guide the rest.":"താഴെ ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കൂ. പൂജയുടെ പേര് അറിയേണ്ടതില്ല—തുടർന്നുള്ള ഘട്ടങ്ങൾ ഞങ്ങൾ കാണിക്കും.","Best place to start":"തുടങ്ങാനുള്ള എളുപ്പവഴി","Help me choose and book":"തിരഞ്ഞെടുക്കാനും ബുക്ക് ചെയ്യാനും സഹായിക്കൂ","Describe the occasion in simple words":"അവസരം ലളിതമായ വാക്കുകളിൽ പറയൂ","Describe":"വിവരിക്കൂ","Choose":"തിരഞ്ഞെടുക്കൂ","Confirm":"സ്ഥിരീകരിക്കൂ","Nearby verified Pandits":"അടുത്തുള്ള പരിശോധിച്ച പണ്ഡിറ്റുകൾ","Choose someone your family can trust":"നിങ്ങളുടെ കുടുംബത്തിന് വിശ്വസിക്കാവുന്ന പണ്ഡിറ്റിനെ തിരഞ്ഞെടുക്കൂ","Only approved, online Pandits inside their service area are shown.":"അംഗീകരിച്ച, ഓൺലൈനിലുള്ള, നിങ്ങളുടെ പ്രദേശത്ത് സേവനം നൽകുന്ന പണ്ഡിറ്റുകൾ മാത്രം കാണിക്കും.","Quick help":"വേഗത്തിലുള്ള സഹായം","Choose what you need now":"ഇപ്പോൾ വേണ്ടത് തിരഞ്ഞെടുക്കൂ","Nothing is submitted until you confirm.":"നിങ്ങൾ സ്ഥിരീകരിക്കുന്നതുവരെ ഒന്നും അയയ്ക്കില്ല.","Plan ahead":"മുൻകൂട്ടി ആസൂത്രണം ചെയ്യൂ","Schedule a Puja":"പൂജ സമയം നിശ്ചയിക്കൂ","Urgent help":"അടിയന്തര സഹായം","My Pandit cancelled":"എന്റെ പണ്ഡിറ്റ് റദ്ദാക്കി","Quickly find another approved Pandit nearby.":"അടുത്തുള്ള മറ്റൊരു അംഗീകരിച്ച പണ്ഡിറ്റിനെ വേഗം കണ്ടെത്തൂ.","Online guidance":"ഓൺലൈൻ മാർഗനിർദേശം","Chat with a Pandit":"പണ്ഡിറ്റുമായി ചാറ്റ് ചെയ്യൂ","Ask a religious question privately online.":"മതപരമായ ചോദ്യം സ്വകാര്യമായി ഓൺലൈനിൽ ചോദിക്കൂ."
  },
};

export function translatePortalText(text: string, language: string) {
  return CUSTOMER_HOME_TRANSLATIONS[language]?.[text] ?? text;
}
