import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { authorizationResponse } from "@/lib/api-auth";
import { recordAdminAction } from "@/lib/admin-audit";
import { sql } from "@/lib/db";
import { notifyUser } from "@/lib/push-notifications";

export const dynamic="force-dynamic";

export async function GET(){try{await requireAdmin();const [eligible,batches]=await Promise.all([
  sql(`SELECT t.id AS transaction_id,t.booking_id,t.amount AS gross_amount,b.pandit_id,u.name AS pandit_name,p.payout_method,COALESCE(v.bank_status,'PENDING') AS bank_status FROM pim_v2.payment_transactions t JOIN pim_v2.bookings b ON b.id=t.booking_id JOIN pim_v2.users u ON u.id=b.pandit_id JOIN pim_v2.pandit_profiles p ON p.user_id=b.pandit_id LEFT JOIN pim_v2.pandit_verification_reviews v ON v.pandit_id=b.pandit_id LEFT JOIN pim_v2.payout_items i ON i.payment_transaction_id=t.id WHERE t.purpose='SERVICE_PAYMENT' AND t.status='CAPTURED' AND i.id IS NULL ORDER BY t.captured_at`),
  sql(`SELECT b.*,COALESCE(json_agg(json_build_object('id',i.id,'panditId',i.pandit_id,'panditName',u.name,'bookingId',i.booking_id,'gross',i.gross_amount,'commission',i.commission_amount,'net',i.net_amount,'status',i.status,'reference',i.reconciliation_reference,'failure',i.failure_reason) ORDER BY u.name) FILTER(WHERE i.id IS NOT NULL),'[]') AS items FROM pim_v2.payout_batches b LEFT JOIN pim_v2.payout_items i ON i.batch_id=b.id LEFT JOIN pim_v2.users u ON u.id=i.pandit_id GROUP BY b.id ORDER BY b.created_at DESC LIMIT 30`),
 ]);return NextResponse.json({eligible:eligible.rows,batches:batches.rows},{headers:{"Cache-Control":"no-store"}});}catch(error){return authorizationResponse(error)??NextResponse.json({error:"Unable to load payouts"},{status:500});}}

export async function POST(request:Request){try{const admin=await requireAdmin();const body=await request.json() as {action?:"CREATE_BATCH"|"APPROVE_BATCH"|"MARK_PAID"|"MARK_FAILED";batchId?:string;itemId?:string;reference?:string;reason?:string};const commission=Math.min(100,Math.max(0,Number(process.env.PLATFORM_COMMISSION_PERCENT)||15));
  if(body.action==="CREATE_BATCH"){const batchId=crypto.randomUUID();const result=await sql<{id:string}>(`WITH eligible AS (SELECT t.id AS transaction_id,t.booking_id,t.amount,b.pandit_id FROM pim_v2.payment_transactions t JOIN pim_v2.bookings b ON b.id=t.booking_id LEFT JOIN pim_v2.payout_items existing ON existing.payment_transaction_id=t.id WHERE t.purpose='SERVICE_PAYMENT' AND t.status='CAPTURED' AND existing.id IS NULL AND b.pandit_id IS NOT NULL),batch AS (INSERT INTO pim_v2.payout_batches(id,period_start,period_end,created_by) SELECT $1,COALESCE(min(t.captured_at),now()),now(),$2 FROM eligible e JOIN pim_v2.payment_transactions t ON t.id=e.transaction_id HAVING count(*)>0 RETURNING id),items AS (INSERT INTO pim_v2.payout_items(id,batch_id,pandit_id,booking_id,payment_transaction_id,gross_amount,commission_amount,net_amount) SELECT gen_random_uuid(),$1,pandit_id,booking_id,transaction_id,amount,round(amount*$3/100.0)::int,amount-round(amount*$3/100.0)::int FROM eligible WHERE EXISTS(SELECT 1 FROM batch) RETURNING *) UPDATE pim_v2.payout_batches b SET gross_amount=x.gross,commission_amount=x.commission,net_amount=x.net FROM (SELECT batch_id,sum(gross_amount)::int gross,sum(commission_amount)::int commission,sum(net_amount)::int net FROM items GROUP BY batch_id)x WHERE b.id=x.batch_id RETURNING b.id`,[batchId,admin.id,commission]);if(!result.rows[0])return NextResponse.json({error:"No captured online service payments are ready for payout"},{status:409});await recordAdminAction(request,admin.id,"PAYOUT_BATCH_CREATED","PAYOUT_BATCH",batchId,{commissionPercent:commission});return NextResponse.json({success:true,batchId},{status:201});}
  if(body.action==="APPROVE_BATCH"&&body.batchId){const result=await sql(`UPDATE pim_v2.payout_batches SET status='APPROVED',approved_by=$2 WHERE id=$1 AND status='DRAFT' RETURNING id`,[body.batchId,admin.id]);if(!result.rows[0])return NextResponse.json({error:"Only a draft batch can be approved"},{status:409});await sql(`UPDATE pim_v2.payout_items SET status=CASE WHEN EXISTS(SELECT 1 FROM pim_v2.pandit_verification_reviews v WHERE v.pandit_id=payout_items.pandit_id AND v.bank_status='VERIFIED') THEN 'PENDING' ELSE 'HELD' END WHERE batch_id=$1`,[body.batchId]);await recordAdminAction(request,admin.id,"PAYOUT_BATCH_APPROVED","PAYOUT_BATCH",body.batchId,{});return NextResponse.json({success:true});}
  if(body.action==="MARK_PAID"&&body.itemId&&body.reference?.trim()){const changed=await sql<{pandit_id:string;batch_id:string;net_amount:number}>(`UPDATE pim_v2.payout_items SET status='PAID',reconciliation_reference=$2,paid_at=now(),failure_reason=NULL WHERE id=$1 AND status IN ('PENDING','PROCESSING','FAILED') RETURNING pandit_id,batch_id,net_amount`,[body.itemId,body.reference.trim().slice(0,150)]);if(!changed.rows[0])return NextResponse.json({error:"Payout item is not payable"},{status:409});await reconcileBatch(changed.rows[0].batch_id);await notifyUser(changed.rows[0].pandit_id,{title:"Payout completed",body:`A payout of ₹${changed.rows[0].net_amount.toLocaleString("en-IN")} was recorded.`,url:"/pandit/settings/payments",eventType:"PAYOUT_COMPLETED"});await recordAdminAction(request,admin.id,"PAYOUT_MARKED_PAID","PAYOUT_ITEM",body.itemId,{reference:body.reference.trim()});return NextResponse.json({success:true});}
  if(body.action==="MARK_FAILED"&&body.itemId&&body.reason?.trim()){const changed=await sql<{pandit_id:string;batch_id:string}>(`UPDATE pim_v2.payout_items SET status='FAILED',failure_reason=$2 WHERE id=$1 AND status<>'PAID' RETURNING pandit_id,batch_id`,[body.itemId,body.reason.trim().slice(0,500)]);if(!changed.rows[0])return NextResponse.json({error:"Payout item cannot be changed"},{status:409});await reconcileBatch(changed.rows[0].batch_id);await notifyUser(changed.rows[0].pandit_id,{title:"Payout needs attention",body:"A payout attempt failed. Check your verified payout details or contact support.",url:"/pandit/settings/payments",eventType:"PAYOUT_FAILED"});await recordAdminAction(request,admin.id,"PAYOUT_MARKED_FAILED","PAYOUT_ITEM",body.itemId,{reason:body.reason.trim()});return NextResponse.json({success:true});}
  return NextResponse.json({error:"Invalid payout action"},{status:400});
 }catch(error){return authorizationResponse(error)??NextResponse.json({error:"Unable to update payouts"},{status:500});}}

async function reconcileBatch(batchId:string){await sql(`UPDATE pim_v2.payout_batches b SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM pim_v2.payout_items WHERE batch_id=b.id AND status<>'PAID') THEN 'COMPLETED' WHEN EXISTS(SELECT 1 FROM pim_v2.payout_items WHERE batch_id=b.id AND status='PAID') AND EXISTS(SELECT 1 FROM pim_v2.payout_items WHERE batch_id=b.id AND status IN ('FAILED','HELD')) THEN 'PARTIAL' WHEN EXISTS(SELECT 1 FROM pim_v2.payout_items WHERE batch_id=b.id AND status='FAILED') THEN 'FAILED' ELSE b.status END,completed_at=CASE WHEN NOT EXISTS(SELECT 1 FROM pim_v2.payout_items WHERE batch_id=b.id AND status<>'PAID') THEN now() ELSE completed_at END WHERE id=$1`,[batchId]);}
