import { createCipheriv, randomBytes } from "node:crypto";
import { appendFile, mkdir, writeFile } from "node:fs/promises";
import { createWriteStream } from "node:fs";
import { spawn } from "node:child_process";
import { pipeline } from "node:stream/promises";
import path from "node:path";

const connection=process.env.DIRECT_URL||process.env.DATABASE_URL;
const rawKey=process.env.BACKUP_ENCRYPTION_KEY?.trim();
if(!connection)throw new Error("DIRECT_URL or DATABASE_URL is required");
if(!rawKey)throw new Error("BACKUP_ENCRYPTION_KEY is required");
const key=Buffer.from(rawKey,"base64");
if(key.length!==32)throw new Error("BACKUP_ENCRYPTION_KEY must be a base64-encoded 32-byte key");
const directory=path.resolve(process.env.BACKUP_DIRECTORY||".backups");
await mkdir(directory,{recursive:true});
const stamp=new Date().toISOString().replaceAll(":","-").replaceAll(".","-");
const output=path.join(directory,`panditconnect-${stamp}.dump.enc`);
const iv=randomBytes(12);
const cipher=createCipheriv("aes-256-gcm",key,iv);
await writeFile(output,Buffer.concat([Buffer.from("PIMBACKUP1"),iv]),{mode:0o600});
const dump=spawn("pg_dump",["--format=custom","--no-owner","--no-privileges","--schema=pim_v2",connection],{stdio:["ignore","pipe","pipe"]});
let stderr="";dump.stderr.on("data",chunk=>stderr+=chunk.toString());
const completion=new Promise((resolve,reject)=>{dump.once("error",reject);dump.once("close",resolve);});
const encryptedOutput=createWriteStream(output,{flags:"a",mode:0o600});
const [,exit]=await Promise.all([pipeline(dump.stdout,cipher,encryptedOutput),completion]);
if(exit!==0)throw new Error(`pg_dump failed: ${stderr.slice(0,500)}`);
await appendFile(output,cipher.getAuthTag());
console.log(JSON.stringify({success:true,file:output,encrypted:true,schema:"pim_v2"}));
