import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { authorizationResponse } from "@/lib/api-auth";
import { recordAdminAction } from "@/lib/admin-audit";
import { sql } from "@/lib/db";
import { createProviderRefund } from "@/lib/payment-provider";
import { notifyUser } from "@/lib/push-notifications";

export async function GET(){try{await requireAdmin();const result=await sql(`SELECT r.*,t.user_id,t.amount AS paid_amount,t.provider_payment_id,u.name AS customer_name,right(u.phone,4) AS phone_suffix FROM pim_v2.refunds r JOIN pim_v2.payment_transactions t ON t.id=r.payment_transaction_id JOIN pim_v2.users u ON u.id=t.user_id ORDER BY r.created_at DESC LIMIT 100`);return NextResponse.json({refunds:result.rows},{headers:{"Cache-Control":"no-store"}});}catch(error){return authorizationResponse(error)??NextResponse.json({error:"Unable to load refunds"},{status:500});}}

export async function POST(request:Request){try{const admin=await requireAdmin();const body=await request.json() as {transactionId?:string;supportCaseId?:string;amount?:number;reason?:string};const amount=Math.floor(Number(body.amount));if(!body.transactionId||!body.reason?.trim()||!Number.isFinite(amount)||amount<=0)return NextResponse.json({error:"Transaction, amount and reason are required"},{status:400});const payment=await sql<{id:string;user_id:string;amount:number;provider_payment_id:string|null;status:string}>(`SELECT id,user_id,amount,provider_payment_id,status FROM pim_v2.payment_transactions WHERE id=$1`,[body.transactionId]);const p=payment.rows[0];if(!p||p.status!=="CAPTURED"||!p.provider_payment_id)return NextResponse.json({error:"Only a captured provider payment can be refunded"},{status:409});const refunded=await sql<{total:number}>(`SELECT COALESCE(sum(amount),0)::int total FROM pim_v2.refunds WHERE payment_transaction_id=$1 AND status NOT IN ('FAILED','REJECTED')`,[p.id]);if(amount+(refunded.rows[0]?.total??0)>p.amount)return NextResponse.json({error:"Refund exceeds the remaining captured amount"},{status:409});const id=crypto.randomUUID();await sql(`INSERT INTO pim_v2.refunds(id,payment_transaction_id,support_case_id,amount,reason,status,requested_by,approved_by) VALUES($1,$2,$3,$4,$5,'APPROVED',$6,$6)`,[id,p.id,body.supportCaseId||null,amount,body.reason.trim().slice(0,1000),admin.id]);const provider=await createProviderRefund(p.provider_payment_id,amount,{refundId:id,reason:body.reason.trim().slice(0,200)});await sql(`UPDATE pim_v2.refunds SET status='PROCESSING',provider_refund_id=$2,updated_at=now() WHERE id=$1`,[id,provider.id]);await sql(`UPDATE pim_v2.payment_transactions SET status='REFUND_PENDING',updated_at=now() WHERE id=$1`,[p.id]);await recordAdminAction(request,admin.id,"REFUND_INITIATED","REFUND",id,{transactionId:p.id,amount,providerRefundId:provider.id});await notifyUser(p.user_id,{title:"Refund initiated",body:`A refund of ₹${amount.toLocaleString("en-IN")} has been sent to the original payment method.`,url:"/customer#support",eventType:"REFUND_INITIATED"});return NextResponse.json({success:true,refundId:id,providerRefundId:provider.id},{status:201});}catch(error){return authorizationResponse(error)??NextResponse.json({error:error instanceof Error?error.message:"Unable to initiate refund"},{status:500});}}
